name: release

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    if: startsWith(github.event.head_commit.message, '[release]')
    strategy:
      matrix:
        os: [windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install gcc-10
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
      - name: Install conan
        run: |
          python -m pip install --upgrade pip
          pip install conan --upgrade
          pip install conan_package_tools --upgrade
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add wumo https://api.bintray.com/conan/wumo/public
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '9'
          java-package: jdk
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
        run: |
          ./gradlew generateJava
          ./gradlew generateJNI
      - name: Upload resources
        uses: actions/upload-artifact@v2
        with:
          name: windows-resources
          path: src/main/resources

  build-linux:
    needs: build-windows
    if: startsWith(github.event.head_commit.message, '[release]')
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Download resources
        uses: actions/download-artifact@v2
        with:
          name: windows-resources
          path: src/main/resources
      - name: Display structure of downloaded files
        run: ls -R
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install gcc-10
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
      - name: Install conan
        run: |
          python -m pip install --upgrade pip
          pip install conan --upgrade
          pip install conan_package_tools --upgrade
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add wumo https://api.bintray.com/conan/wumo/public
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '9'
          java-package: jdk
          architecture: x64
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
          GRAALVM_HOME: ${{ env.JAVA_HOME }}
        run: |
          ./gradlew generateJava
          ./gradlew generateJNI
      - name: Upload resources
        uses: actions/upload-artifact@v2
        with:
          name: resources
          path: src/main/resources

  commit-release:
    needs: build-linux
    if: startsWith(github.event.head_commit.message, '[release]')
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: true
          fetch-depth: 0
      - name: Download resources
        uses: actions/download-artifact@v2
        with:
          name: resources
          path: src/main/resources
      - name: Commit files
        run: |
          git config --local user.email "wumo@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Compiled library resources" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}