name: release

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    if: startsWith(github.event.head_commit.message, '[release]')
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install conan
        run: |
          python -m pip install --upgrade pip
          pip install conan --upgrade
          pip install conan_package_tools --upgrade
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add wumo https://api.bintray.com/conan/wumo/public
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '9'
          java-package: jdk
          architecture: x64
      - name: Build with Gradle
        run: |
          ./gradlew generateJava
          ./gradlew generateJNI
      - name: Upload resources
        uses: actions/upload-artifact@v2
        with:
          name: windows-resources
          path: src/main/resources

  build-linux:
    if: startsWith(github.event.head_commit.message, '[release]')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Install gcc-10
        run: |
          sudo apt install gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 60 --slave /usr/bin/g++ g++ /usr/bin/g++-10
      - name: Install conan
        run: |
          python -m pip install --upgrade pip
          pip install conan --upgrade
          pip install conan_package_tools --upgrade
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          conan remote add wumo https://api.bintray.com/conan/wumo/public
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '9'
          java-package: jdk
          architecture: x64
      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew generateJava
          ./gradlew generateJNI
      - name: Upload resources
        uses: actions/upload-artifact@v2
        with:
          name: linux-resources
          path: src/main/resources

  commit-release:
    if: startsWith(github.event.head_commit.message, '[release]')
    needs: [ build-windows, build-linux ]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: true
          fetch-depth: 0
      - name: Download linux-resources
        uses: actions/download-artifact@v2
        with:
          name: linux-resources
          path: src/main/resources
      - name: Download windows-resources
        uses: actions/download-artifact@v2
        with:
          name: windows-resources
          path: src/main/resources
      - name: Commit files
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git add src/main/resources
          git commit -m "Compiled library resources" -a
      - name: Push changes to ci branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ci
          force: true
      - name: Get release version
        run: |
          chmod +x gradlew
          echo ::set-env name=PROJECT_VERSION::$(./gradlew properties -q | grep "version:" | awk '{print $2}')
      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.PROJECT_VERSION }}
          release_name: ${{ env.PROJECT_VERSION }}
          commitish: ci
      - name: Trigger jitpack.io build
        run: |
          curl --silent --output /dev/null https://jitpack.io/#$GITHUB_REPOSITORY/$PROJECT_VERSION